### ISSUE TITLE
Goturn tracker fails to allocate 95GB of RAM

### ISSUE THREAD

**Issue by mipko** [opencv/opencv_contrib#2426]
##### System information (version)

- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 19.10 64bit
- Compiler => gcc 8

##### Detailed description

I have tried to use goturn tracker and it fails with error not being able to allocate 95GB of memory. 
I have compiled the OpenCV with CUDA enabled flags, however goturn fails with the same error if I use non CUDA enabled OpenCV build

I have used caffe prototxt and caffemodel files available.

##### Steps to reproduce

```
Ptr<Tracker> tracker = TrackerGOTURN::create()
tracker->init(frame, bbox)'

```
##### Error

```.cpp terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) /home/mirko/programiranje/ocv42install/opencv/modules/core/src/alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 95588562276 bytes in function 'OutOfMemoryError'

**Comment by AlexGatz** [comment]
Having the same issue with python as well. Same OpenCV version.

**Comment by AlexGatz** [comment]
Tested:
- OpenCV: 3.4.8.29
Odd result. Ran for a short time as expected then hit another memory error.

**Comment by AlexGatz** [comment]
So it appears that the bounding box is growing large enough to cause the memory issue. I'm going to try to limit its size and see if that fixes the issue.

**Comment by mipko** [comment]
the culprit of the problem for OpenCV 4.2.0 is not in inference itself. Loading caffe model causes the error. It doesn't reach the inference at all.

**Comment by ammarnabbas** [comment]
Works fine with python2.7 and openCV3.X.X

**Comment by berak** [comment]
> Loading caffe model causes the error.

can be reproduced with opencv4.x like:

    net = cv2.dnn.readNet("goturn.caffemodel", "goturn.prototxt")

**Comment by Mortiniera** [comment]
Same issue with python as well : 

OS: Arch Windows 64bit
OpenCV: 4.2.0

Any idea on how to fix this ?

**Comment by alalek** [comment]
Please try patch from here: https://github.com/opencv/opencv/pull/16617

**Comment by dkurt** [comment]
Hi! As temporal workaround please try to comment the following lines:
```yaml
input: "data1"
# input_dim: 1
# input_dim: 3
# input_dim: 227
# input_dim: 227

input: "data2"
# input_dim: 1
# input_dim: 3
# input_dim: 227
# input_dim: 227
```

Sorry for inconvenience!

**Comment by ykchong45** [comment]
> Hi! As a temporal workaround please try to comment the following lines:

The error dismissed once I commented on lines in the `goturn.caffemodel.prototxt`.
