### ISSUE TITLE
error: no instance of overloaded function "cv::cudev::blockReduce" matches the argument list

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv_contrib#3728]
##### System information (version)

- OpenCV => :grey_question: 5.X
- Operating System / Platform => :grey_question: Ubuntu 24.04 LTS
- Compiler => :grey_question: gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

##### Steps to reproduce

Just trying to build **OpenCV-5.x** with **OpenCV_contrib-5.x**, and I got the following **ERROR** messages:

```
....../opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/reduce.hpp(385): error: no instance of overloaded function "cv::cudev::blockReduce" matches the argument list
            argument types are: (cuda::std::__4::tuple<volatile int *, volatile int *>, cuda::std::__4::tuple<int &, int &>, int, cuda::std::__4::tuple<cv::cudev::minimum<int>, cv::cudev::maximum<int>>)
              blockReduce<BLOCK_SIZE, volatile double *, double, cv::cudev::minimum<double>, cv::cudev::maximum<double>>(smem_tuple(sminval, smaxval), tie(mymin, mymax), tid, make_tuple(minOp, maxOp));
              ^
....../opencv_contrib/modules/cudev/include/opencv2/cudev/block/reduce.hpp(72): note #3327-D: candidate function template "cv::cudev::blockReduce<N,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,R0,R1,R2,R3,R4,R5,R6,R7,R8,R9,Op0,Op1,Op2,Op3,Op4,Op5,Op6,Op7,Op8,Op9>(const thrust::THRUST_200302_800_860_NS::tuple<P0, P1, P2, P3, P4, P5, P6, P7, P8, P9> &, const thrust::THRUST_200302_800_860_NS::tuple<R0, R1, R2, R3, R4, R5, R6, R7, R8, R9> &, uint, const thrust::THRUST_200302_800_860_NS::tuple<Op0, Op1, Op2, Op3, Op4, Op5, Op6, Op7, Op8, Op9> &)" failed deduction
  __attribute__((device)) __inline__ __attribute__((always_inline)) void blockReduce(const tuple<P0, P1, P2, P3, P4, P5, P6, P7, P8, P9>& smem,
                                                                         ^
....../opencv_contrib/modules/cudev/include/opencv2/cudev/block/reduce.hpp(63): note #3323-D: substituting explicit template arguments "<<expression>, volatile double *, double, cv::cudev::minimum<double>, cv::cudev::maximum<double>>" for function template "cv::cudev::blockReduce<N,T,Op>(volatile T *, T &, uint, const Op &)" failed
  __attribute__((device)) __inline__ __attribute__((always_inline)) void blockReduce(volatile T* smem, T& val, uint tid, const Op& op)
```

##### Issue submission checklist

 - [X] I report the issue, it's not a question
   
 - [X] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [X] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by LaurentBerger** [comment]
Is it really an issue? Did you check  the problem with documentation, FAQ, open issues,
[forum.opencv.org,](https://forum.opencv.org/t/cmake-build-fail-opencv-4-9-0-cuda-12-4-cudnn-9-1-0-gcc-11-4/17424) Stack Overflow, etc and have not found any solution ?
What is your configuration?
please nobody can help you without configuration. Post your cmake output.

**Comment by cudawarped** [comment]
> Is it really an issue?

Actually its two issues

1) an inability to search 
    https://github.com/search?q=repo%3Aopencv%2Fopencv_contrib+blockReduce%3CBLOCK_SIZE&type=issues

2) https://github.com/opencv/opencv_contrib/issues/3690

**Comment by jiapei100** [comment]
@cudawarped 

Is this working with **CUDA-12.3** ?

**Comment by cudawarped** [comment]
> @cudawarped
> 
> Is this working with **CUDA-12.3** ?

Yes everything works with CUDA 12.3 and cuDNN 8.9.7.

**Comment by jiapei100** [comment]
@cudawarped 

The official release of 4.9.0?
Or git version?

**Comment by jiapei100** [comment]
@cudawarped 

I guess it may have something to do with both **CUDA version** and **GCC version**. As for **CUDNN**, I stick to **8.9.7**.

Since I'm now using **Ubuntu-24.04**, by default, it comes with **gcc-13.2.0**, which seems to be compatible with **cuda-12.4**.

If I downgrade **CUDA** from **12.4** to **12.3**, I got a lot of **this error**:

**error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.** 


Then, I downgraded **GCC** from **13.2.0** to **12.3.0**, but still met exactly the same error as 

```
....../4.x/opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/reduce.hpp(379): error: no instance of overloaded function "cv::cudev::blockReduce" matches the argument list
            argument types are: (thrust::THRUST_200500_800_860_NS::tuple<volatile int *, volatile int *>, thrust::THRUST_200500_800_860_NS::tuple<int &, int &>, int, thrust::THRUST_200500_800_860_NS::tuple<cv::cudev::minimum<int>, cv::cudev::maximum<int>>)
              blockReduce<BLOCK_SIZE>(smem_tuple(sminval, smaxval), tie(mymin, mymax), tid, make_tuple(minOp, maxOp));
              ^
          detected during:
            instantiation of "void cv::cudev::grid_reduce_detail::MinMaxReductor<cv::cudev::grid_reduce_detail::both, src_type, work_type>::reduceGrid<BLOCK_SIZE>(work_type *, int) [with src_type=uchar, work_type=int, BLOCK_SIZE=256]" at line 412
            instantiation of "void cv::cudev::grid_reduce_detail::reduce<Reductor,BLOCK_SIZE,PATCH_X,PATCH_Y,SrcPtr,ResType,MaskPtr>(SrcPtr, ResType *, MaskPtr, int, int) [with Reductor=cv::cudev::grid_reduce_detail::MinMaxReductor<cv::cudev::grid_reduce_detail::both, uchar, int>, BLOCK_SIZE=256, PATCH_X=4, PATCH_Y=4, SrcPtr=cv::cudev::GlobPtr<uchar>, ResType=int, MaskPtr=cv::cudev::WithOutMask]" at line 421
            instantiation of "void cv::cudev::grid_reduce_detail::reduce<Reductor,Policy,SrcPtr,ResType,MaskPtr>(const SrcPtr &, ResType *, const MaskPtr &, int, int, cudaStream_t) [with Reductor=cv::cudev::grid_reduce_detail::MinMaxReductor<cv::cudev::grid_reduce_detail::both, uchar, int>, Policy=cv::cudev::DefaultGlobReducePolicy, SrcPtr=cv::cudev::GlobPtr<uchar>, ResType=int, MaskPtr=cv::cudev::WithOutMask]" at line 460
            instantiation of "void cv::cudev::grid_reduce_detail::minMaxVal<Policy,SrcPtr,ResType,MaskPtr>(const SrcPtr &, ResType *, const MaskPtr &, int, int, cudaStream_t) [with Policy=cv::cudev::DefaultGlobReducePolicy, SrcPtr=cv::cudev::GlobPtr<uchar>, ResType=int, MaskPtr=cv::cudev::WithOutMask]" at line 206 of ....../4.x/opencv_contrib/modules/cudev/include/opencv2/cudev/grid/reduce.hpp
            instantiation of "void cv::cudev::gridFindMinMaxVal_<Policy,SrcPtr,ResType>(const SrcPtr &, cv::cudev::GpuMat_<ResType> &, cv::cuda::Stream &) [with Policy=cv::cudev::DefaultGlobReducePolicy, SrcPtr=cv::cudev::GpuMat_<uchar>, ResType=int]" at line 349 of ....../4.x/opencv_contrib/modules/cudev/include/opencv2/cudev/grid/reduce.hpp
            instantiation of "void cv::cudev::gridFindMinMaxVal(const SrcPtr &, cv::cudev::GpuMat_<ResType> &, cv::cuda::Stream &) [with SrcPtr=cv::cudev::GpuMat_<uchar>, ResType=int]" at line 68 of ....../4.x/opencv_contrib/modules/cudaarithm/src/cuda/minmax.cu
            instantiation of "void <unnamed>::minMaxImpl<T,R>(const cv::cuda::GpuMat &, const cv::cuda::GpuMat &, cv::cuda::GpuMat &, cv::cuda::Stream &) [with T=uchar, R=int]" at line 92 of ....../4.x/opencv_contrib/modules/cudaarithm/src/cuda/minmax.cu

....../4.x/opencv_contrib/modules/cudev/include/opencv2/cudev/grid/detail/reduce.hpp(379): error: no instance of overloaded function "cv::cudev::blockReduce" matches the argument list
            argument types are: (thrust::THRUST_200500_800_860_NS::tuple<volatile int *, volatile int *>, thrust::THRUST_200500_800_860_NS::tuple<int &, int &>, int, thrust::THRUST_200500_800_860_NS::tuple<cv::cudev::minimum<int>, cv::cudev::maximum<int>>)
              blockReduce<BLOCK_SIZE>(smem_tuple(sminval, smaxval), tie(mymin, mymax), tid, make_tuple(minOp, maxOp));
              ^
          detected during:
```


Hmm.... no idea. Maybe the installed [https://github.com/NVIDIA/cccl](https://github.com/NVIDIA/cccl) ???

**Comment by jiapei100** [comment]
yeah.... Problem solved by just **Turn OFF rgbd**... Thanks

**Comment by peihuang0404** [comment]
> rgbd

please tell us, how to  **Turn OFF rgbd**, thanks!

**Comment by JzHuai0108** [comment]
I ran into this heartbreaking problem when I try to build opencv with cuda and cudnn installed with conda in the conda environment.
The cuda and cudnn are installed in the conda env by 
```
conda install nvidia/label/cuda-12.1.0::cuda-nvcc
conda install nvidia/label/cuda-12.1.0::cuda-toolkit
conda install -c conda-forge cudnn
```

"nvcc --version" shows normally, "conda list cudnn" also no problem.
The command to build opencv
```
export VIRTUAL_PYTHON_PATH=/home/pi/miniconda3/envs/opencv_env
cmake -D CMAKE_BUILD_TYPE=RELEASE \
	-D CMAKE_INSTALL_PREFIX=/home/pi/Documents/slam_devel \
	-D INSTALL_PYTHON_EXAMPLES=ON \
	-D INSTALL_C_EXAMPLES=OFF \
	-D OPENCV_ENABLE_NONFREE=ON \
	-D WITH_CUDA=ON \
	-D WITH_CUDNN=ON \
	-D OPENCV_DNN_CUDA=ON \
    -DWITH_NVCUVID=ON \
	-D ENABLE_FAST_MATH=1 \
	-D CUDA_FAST_MATH=1 \
	-D CUDA_ARCH_BIN=7.5 \
	-D WITH_CUBLAS=1 \
	-D OPENCV_EXTRA_MODULES_PATH="../../opencv_contrib-4.10.0/modules" \
    -D BUILD_opencv_python2=OFF \
	-D BUILD_opencv_python3=ON \
    -D PYTHON_DEFAULT_EXECUTABLE=${VIRTUAL_PYTHON_PATH}/bin/python3 \
	-D PYTHON3_EXCUTABLE=${VIRTUAL_PYTHON_PATH}/bin/python3 \
    -D PYTHON3_LIBRARY=${VIRTUAL_PYTHON_PATH}/lib/lib${PYTHON_VERSION}m.so.1.0 \
    -D PYTHON_NUMPY_PATH=${VIRTUAL_PYTHON_PATH}/lib/${PYTHON_VERSION}/site-packages \
    -DBUILD_TIFF=ON -DBUILD_ZLIB=ON -DBUILD_JASPER=ON -DBUILD_CCALIB=ON -DBUILD_JPEG=ON -DWITH_FFMPEG=ON \
	-D BUILD_EXAMPLES=ON ..

```
I tried opencv + opencv contrib {4.7, 4.8, 4.10} x cuda/nvcc {11.8, 12.1, 12.3} + cudnn {8.9.2, 9.1}. None of them worked. 
Is there anything I can do to make it work?

**Comment by JzHuai0108** [comment]
I will try the latest opencv if I got extra time. Right now, I will go with docker which has opencv 4.8 + cuda 11.8 and it works fine. The ultimate reason may be some mis configuration in my conda.
