### PR TITLE
cudacodec: fix #3711 (update for Nvidia Video Codec SDK 12.2)

### LINKED ISSUE #3711: `cudacodec`: `VideoWriter` fails to compile with Nvidia Video Codec SDK 12.2
Nvidia has changed the *nvEncodeAPI.h* interface in the new Video Codec SDK 12.2 replacing

```
NV_ENC_CONFIG_HEVC::pixelBitDepthMinus8 - Specifies pixel bit depth minus 8.
```

with

```
NV_ENC_CONFIG_HEVC::outputBitDepth - Specifies pixel bit depth of encoded video.
NV_ENC_CONFIG_HEVC::inputBitDepth - Specifies pixel bit depth of video input.
```

resulting in the following compilation errors when building `opencv_cudacodec`

> D:\repos\opencv\contrib\modules\cudacodec\src\NvEncoder.cpp(119): error C2039: 'pixelBitDepthMinus8': is not a member of '_NV_ENC_CONFIG_HEVC'
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\nvEncodeAPI.h(1820): note: see declaration of '_NV_ENC_CONFIG_HEVC'
> D:\repos\opencv\contrib\modules\cudacodec\src\NvEncoder.cpp(174): error C2039: 'pixelBitDepthMinus8': is not a member of '_NV_ENC_CONFIG_HEVC'
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\include\nvEncodeAPI.h(1820): note: see declaration of '_NV_ENC_CONFIG_HEVC'

##### System information (version)
- OpenCV => 4.9
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022

##### Steps to reproduce

Build `opencv_cudacodec` against Nvidia Video Codec SDK 12.2

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by cudawarped**
fix #3711 by updating *NVEncoder.cpp* to reflect the changes contained in Nvidia's sample code.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]

**Comment by Jerry-Master** [comment]
This PR fails for version 13 due to the way the if else is coded. Using #if ((NVENCAPI_MAJOR_VERSION >= 12 && NVENCAPI_MINOR_VERSION >= 2) || NVENCAPI_MAJOR_VERSION >= 13) should fix that issue.

**Comment by cudawarped** [comment]
@Jerry-Master See https://github.com/opencv/opencv_contrib/pull/3880/

**Comment by Jerry-Master** [comment]
I was compiling version 4.11, it is good to know that it is fixed in the latest version. Thanks for the fast response.
