### ISSUE TITLE
CUDA_Arithm/ThresholdOtsu.Accuracy/0 fails on Jetson NANO (old one)

### ISSUE THREAD

**Issue by asmorkalov** [opencv/opencv_contrib#3962]
CUDA: 10.2
GCC: 7.5.0
CUDA CC: 5.3

Command:
```
./bin/opencv_test_cudaarithm --gtest_filter=CUDA_Arithm/ThresholdOtsu.Accuracy*
```

Logs:
```
[==========] Running 20 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 20 tests from CUDA_Arithm/ThresholdOtsu
[ RUN      ] CUDA_Arithm/ThresholdOtsu.Accuracy/0, where GetParam() = (NVIDIA Tegra X1, 128x128, 8UC1, Channels(1), cv::THRESH_BINARY, whole matrix)
unknown file: Failure
C++ exception with description "OpenCV(4.12.0-pre) /mnt/disk/opencv/opencv/modules/core/src/cuda/gpu_mat.cu:264: error: (-217:Gpu API call) unspecified launch failure in function 'download'
" thrown in the test body.
[  FAILED  ] CUDA_Arithm/ThresholdOtsu.Accuracy/0, where GetParam() = (NVIDIA Tegra X1, 128x128, 8UC1, Channels(1), cv::THRESH_BINARY, whole matrix) (1031 ms)
[ RUN      ] CUDA_Arithm/ThresholdOtsu.Accuracy/1, where GetParam() = (NVIDIA Tegra X1, 128x128, 8UC1, Channels(1), cv::THRESH_BINARY, sub matrix)
unknown file: Failure
C++ exception with description "OpenCV(4.12.0-pre) /mnt/disk/opencv/opencv/modules/core/src/cuda_info.cpp:74: error: (-217:Gpu API call) all CUDA-capable devices are busy or unavailable in function 'setDevice'
" thrown in SetUp().
[  FAILED  ] CUDA_Arithm/ThresholdOtsu.Accuracy/1, where GetParam() = (NVIDIA Tegra X1, 128x128, 8UC1, Channels(1), cv::THRESH_BINARY, sub matrix) (0 ms)
[ RUN      ] CUDA_Arithm/ThresholdOtsu.Accuracy/2, where GetParam() = (NVIDIA Tegra X1, 128x128, 8UC1, Channels(1), cv::THRESH_BINARY_INV, whole matrix)
unknown file: Failure
C++ exception with description "OpenCV(4.12.0-pre) /mnt/disk/opencv/opencv/modules/core/src/cuda_info.cpp:74: error: (-217:Gpu API call) all CUDA-capable devices are busy or unavailable in function 'setDevice'
" thrown in SetUp().
[  FAILED  ] CUDA_Arithm/ThresholdOtsu.Accuracy/2, where GetParam() = (NVIDIA Tegra X1, 128x128, 8UC1, Channels(1), cv::THRESH_BINARY_INV, whole matrix) (0 ms)
...
```

**Comment by asmorkalov** [comment]
cc @cudawarped

**Comment by cudawarped** [comment]
@asmorkalov Working on Windows with CUDA toolkit 10.2, PTX CC 5.3 on an RTX 3070 Ti Mobile.  I'll try to test on ubuntu later to rule that out but thats as far as I can go as I don't have a compute capability 5.3 device to test on.  A shot in the dark is that `_shfl_down` may not be supported at the hardware level although I would expect compile errors not

> CUDA-capable devices are busy or unavailable

If you have chance you could try this PR to see if it fixes it https://github.com/opencv/opencv_contrib/pull/3963

**Comment by asmorkalov** [comment]
No, the patch does not help.
